2018-09-05 16:58:34,624:DEBUG    


2018-09-05 16:58:34,624:INFO     SERVICE INITIALIZED
2018-09-05 16:58:42,035:DEBUG    LOG =DEBUG
2018-09-05 16:58:42,035:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 16:58:42,035:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 16:58:52,184:INFO     SERVICE CONFIGURATION - LOG =DEBUG - 10.102.81.61:22, user=root, password=cavium.lte (10.15 s)
2018-09-05 16:58:52,194:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 16:58:52,207:DEBUG    Exit code= 0
2018-09-05 16:58:52,207:DEBUG    Jan  1 00:00:19 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1402]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1403]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1403]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1441]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1441]: crond: USER root pid 3025 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1441]: crond: USER root pid 5281 cmd /usr/bin/tempcheck.sh
Jan  2 08:02:23 LSM daemon.info init: starting pid 5662, tty '/dev/ttyS0': '/sbin/getty -L ttyS0 115200 vt100 '
Jan  2 00:03:01 LSM cron.info crond[1441]: crond: USER root pid 6505 cmd /usr/bin/tempcheck.sh
Jan  2 00:04:01 LSM cron.info crond[1441]: crond: USER root pid 8542 cmd /usr/bin/tempcheck.sh
Jan  2 00:05:01 LSM cron.info crond[1441]: crond: USER root pid 9699 cmd /usr/bin/tempcheck.sh
Jan  2 00:06:01 LSM cron.info crond[1441]: crond: USER root pid 9964 cmd /usr/bin/tempcheck.sh
Jan  2 00:07:01 LSM cron.info crond[1441]: crond: USER root pid 10216 cmd /usr/bin/tempcheck.sh
Jan  2 00:08:01 LSM cron.info crond[1441]: crond: USER root pid 10470 cmd /usr/bin/tempcheck.sh
Jan  2 00:09:01 LSM cron.info crond[1441]: crond: USER root pid 10722 cmd /usr/bin/tempcheck.sh
Jan  2 00:10:01 LSM cron.info crond[1441]: crond: USER root pid 10976 cmd /usr/bin/tempcheck.sh
Jan  2 00:11:01 LSM cron.info crond[1441]: crond: USER root pid 11230 cmd /usr/bin/tempcheck.sh
Jan  2 00:12:01 LSM cron.info crond[1441]: crond: USER root pid 11482 cmd /usr/bin/tempcheck.sh
Jan  2 00:13:01 LSM cron.info crond[1441]: crond: USER root pid 11736 cmd /usr/bin/tempcheck.sh
Jan  2 00:14:01 LSM cron.info crond[1441]: crond: USER root pid 11990 cmd /usr/bin/tempcheck.sh
Jan  2 00:15:01 LSM cron.info crond[1441]: crond: USER root pid 12242 cmd /usr/bin/tempcheck.sh
Jan  2 00:16:01 LSM cron.info crond[1441]: crond: USER root pid 12496 cmd /usr/bin/tempcheck.sh
Jan  2 00:17:01 LSM cron.info crond[1441]: crond: USER root pid 12750 cmd /usr/bin/tempcheck.sh
Jan  2 00:18:01 LSM cron.info crond[1441]: crond: USER root pid 12992 cmd /usr/bin/tempcheck.sh
Jan  2 00:19:01 LSM cron.info crond[1441]: crond: USER root pid 13246 cmd /usr/bin/tempcheck.sh
Jan  2 00:20:01 LSM cron.info crond[1441]: crond: USER root pid 13498 cmd /usr/bin/tempcheck.sh
Jan  2 00:21:01 LSM cron.info crond[1441]: crond: USER root pid 13752 cmd /usr/bin/tempcheck.sh
Jan  2 00:22:01 LSM cron.info crond[1441]: crond: USER root pid 14006 cmd /usr/bin/tempcheck.sh
Jan  2 00:23:01 LSM cron.info crond[1441]: crond: USER root pid 14258 cmd /usr/bin/tempcheck.sh
Jan  2 00:24:01 LSM cron.info crond[1441]: crond: USER root pid 14512 cmd /usr/bin/tempcheck.sh
Jan  2 00:25:01 LSM cron.info crond[1441]: crond: USER root pid 14766 cmd /usr/bin/tempcheck.sh
Jan  2 00:26:01 LSM cron.info crond[1441]: crond: USER root pid 15018 cmd /usr/bin/tempcheck.sh
Jan  2 00:27:01 LSM cron.info crond[1441]: crond: USER root pid 15272 cmd /usr/bin/tempcheck.sh
Jan  2 00:28:01 LSM cron.info crond[1441]: crond: USER root pid 15526 cmd /usr/bin/tempcheck.sh
Jan  2 00:29:01 LSM cron.info crond[1441]: crond: USER root pid 15778 cmd /usr/bin/tempcheck.sh
Jan  2 00:30:01 LSM cron.info crond[1441]: crond: USER root pid 16032 cmd /usr/bin/tempcheck.sh
Jan  2 00:31:01 LSM cron.info crond[1441]: crond: USER root pid 16283 cmd /usr/bin/tempcheck.sh
Jan  2 00:32:01 LSM cron.info crond[1441]: crond: USER root pid 16528 cmd /usr/bin/tempcheck.sh
Jan  2 00:33:01 LSM cron.info crond[1441]: crond: USER root pid 16782 cmd /usr/bin/tempcheck.sh
Jan  2 00:34:01 LSM cron.info crond[1441]: crond: USER root pid 17034 cmd /usr/bin/tempcheck.sh
Jan  2 00:35:01 LSM cron.info crond[1441]: crond: USER root pid 17288 cmd /usr/bin/tempcheck.sh
Jan  2 00:36:01 LSM cron.info crond[1441]: crond: USER root pid 17542 cmd /usr/bin/tempcheck.sh
Jan  2 00:37:01 LSM cron.info crond[1441]: crond: USER root pid 17794 cmd /usr/bin/tempcheck.sh
Jan  2 00:38:01 LSM cron.info crond[1441]: crond: USER root pid 18048 cmd /usr/bin/tempcheck.sh
2018-09-05 16:58:52,209:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 16:59:02,348:DEBUG    Timeout 10.0s, TTY=False. Command: fprintenv mode
2018-09-05 16:59:02,381:DEBUG    Exit code= 0
2018-09-05 16:59:02,381:DEBUG    Environment Name = 'mode', Value= 'pltd'.
2018-09-05 16:59:02,381:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fprintenv mode (0.03 s)
2018-09-05 16:59:02,398:DEBUG    Timeout 10.0s, TTY=False. Command: cd /mnt/app; find -maxdepth 1 ! -name ssh ! -name .ssh ! -name env ! -name ubootenv ! -name .sign1985 ! -name passwd ! -name shadow -exec rm -rf {} \;
2018-09-05 16:59:04,598:DEBUG    Exit code= 0
2018-09-05 16:59:04,598:DEBUG    (STDERR)rm: can't remove '.' or '..'
2018-09-05 16:59:04,598:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cd /mnt/app; find -maxdepth 1 ! -name ssh ! -name .ssh ! -name env ! -name ubootenv ! -name .sign1985 ! -name passwd ! -name shadow -exec rm -rf {} \; (2.2 s)
2018-09-05 16:59:05,086:DEBUG    Timeout 200.0s, TTY=False. Command: update -o /tmp/lsm_os.gz; update -b /tmp/lsm_os.gz
2018-09-05 16:59:05,131:DEBUG    Exit code= 0
2018-09-05 16:59:05,131:DEBUG    Image CRC '/tmp/lsm_os.gz' and '/dev/flash_os0' is same - Skip.
Image CRC '/tmp/lsm_os.gz' and '/dev/flash_os1' is same - Skip.
2018-09-05 16:59:05,131:INFO     SERVICE HANDLING - Timeout 200.0s, TTY=False. Command: update -o /tmp/lsm_os.gz; update -b /tmp/lsm_os.gz (0.05 s)
2018-09-05 16:59:09,197:DEBUG    Timeout 1200.0s, TTY=False. Command: update -o /tmp/lsm_rd.gz; update -b /tmp/lsm_rd.gz
2018-09-05 16:59:09,242:DEBUG    Exit code= 0
2018-09-05 16:59:09,242:DEBUG    Image CRC '/tmp/lsm_rd.gz' and '/dev/flash_rd0' is same - Skip.
Image CRC '/tmp/lsm_rd.gz' and '/dev/flash_rd1' is same - Skip.
2018-09-05 16:59:09,242:INFO     SERVICE HANDLING - Timeout 1200.0s, TTY=False. Command: update -o /tmp/lsm_rd.gz; update -b /tmp/lsm_rd.gz (0.04 s)
2018-09-05 16:59:09,387:DEBUG    Timeout 50.0s, TTY=False. Command: update-uboot -n /tmp/u-boot-octeon_tip.bin
2018-09-05 16:59:20,081:DEBUG    Exit code= 0
2018-09-05 16:59:20,081:DEBUG    Updating Normal u-boot...
2018-09-05 16:59:20,081:DEBUG    (STDERR)2+1 records in
2+1 records out
757024 bytes (739.3KB) copied, 10.635846 seconds, 69.5KB/s
2018-09-05 16:59:20,081:INFO     SERVICE HANDLING - Timeout 50.0s, TTY=False. Command: update-uboot -n /tmp/u-boot-octeon_tip.bin (10.69 s)
2018-09-05 17:00:43,003:DEBUG    Timeout 10.0s, TTY=False. Command: ls -l /mnt/app
2018-09-05 17:00:43,019:DEBUG    Exit code= 0
2018-09-05 17:00:43,019:DEBUG    -rw-r--r--    1 root     root       3892930 Jan  2 00:39 Dimark_Client.tgz
-rw-r--r--    1 root     root       2759575 Jan  2 00:39 LFMSOFT_OCT_D.tgz
-rw-r--r--    1 root     root        635321 Jan  2 00:38 data-model.xml
-rw-r--r--    1 root     root        448960 Jan  2 00:39 dsp.tgz
-rw-r--r--    1 root     root           985 Jan  2 00:39 e2eenv.txt
drwxr-xr-x    2 root     root             0 Dec 31 16:00 env
-rw-r--r--    1 root     root       2901563 Jan  2 00:40 lsmD.gz
-rw-r--r--    1 root     root           101 Dec 31 16:01 passwd
-rw-r--r--    1 root     root           161 Jan  2 00:40 rc_post.local
-rw-r--r--    1 root     root            81 Jan  2 00:40 rc_pre.local
-rw-r--r--    1 root     root        185723 Jan  2 00:40 rffe.tgz
-rw-r--r--    1 root     root            68 Dec 31 16:01 shadow
drwxr-xr-x    2 root     root             0 Jan  2 00:00 ssh
-rw-r--r--    1 root     root         47798 Jan  2 00:40 startup.cfg
-rw-r--r--    1 root     root          1747 Jan  2 00:40 tftpenv.txt
-rw-r--r--    1 root     root          1880 Dec 31 16:00 ubootenv
-rw-r--r--    1 root     root           157 Jan  2 00:40 update_rffe.sh
2018-09-05 17:00:43,019:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: ls -l /mnt/app (0.02 s)
2018-09-05 17:00:43,039:DEBUG    Timeout 10.0s, TTY=False. Command: fprintenv
2018-09-05 17:00:43,088:DEBUG    Exit code= 0
2018-09-05 17:00:43,088:DEBUG    CRC check OK(0x89d76480)

atten1=18
atten2=18
autoload=n
baudrate=115200
baudrate_uart1=19200
bf=bootoct $(flash_unused_addr) forceboot numcores=$(numcores)
boardname=zen
bootby=tftp
bootcbyflash=gunzip 0x17e20000 0x20000000; cp.l 0x18320000 0x30800000 0xA00000; bootoctlinux 0x20000000 coremask=0x7 endbootargs rd_name=initrd mem=512M;
bootcbytftp=tftp 0x21000000 lsm_os.gz; gunzip 0x21000000 0x20000000 0x1000000; tftp 0x30800000 lsm_rd.gz; bootoctlinux 0x20000000 coremask=0x7 endbootargs rd_name=initrd mem=512M;
bootcmd=run i2cinit; run namedalloc; run bootcby${bootby}
bootdelay=0
burn_app=erase $(flash_unused_addr) +$(filesize);cp.b $(fileaddr) $(flash_unused_addr) $(filesize)
bw=20
cfgloadby=tftp
dhcpenable=0
dnsip=8.8.8.8
enable_zen5_gpio18=1
enbctrlrf=1
ethact=octeth0
ethaddr=00:D0:CC:20:14:2E
gain1=25
gain2=25
gatewayip=10.102.81.1
httpdenable=1
i2cinit=i2c dev 0; i2c probe; i2c dev 1; i2c probe
ipaddr=10.102.81.61
linux_cf=fatload ide 0 $(loadaddr) vmlinux.64;bootoctlinux $(loadaddr)
loadaddr=0x20000000
logdispen=2
ls=fatls ide 0
mk_ubootenv=1
mode=pltd
mode_test=dl
mtdids=nor0=octeon_nor0
named_block_addr=0x30800000
named_block_size=0x2800000
namedalloc=namedalloc dsp-dump 0x400000 0x7f4D0000; namedalloc cazac 0x630000 0x7f8D0000; namedalloc cpu-dsp-if 0x100000 0x7ff00000; namedalloc dsp-log-buf 0x4000000 0x80000000; namedalloc initrd 0x2800000 0x30800000;
netmask=255.255.255.0
numcores=4
ovrdrfdsp=1
partition=nor0,5
pseudowww=1
ptp1ppsen=0
ptpenable=0
pwdb_in_flash=1
pwmreghigh=24744
pwmreglow=37376
rftarget=ad9362
rxfreq=1730
serverip=10.102.81.50
startapp=0
swloadby=tftp
syncby=gps
target=zen
tcxo=pwm
tip=1
txfreq=1825
txpower=30
ucliovrd=1
web_pass=456b7016a916a4b178dd72b947c152b7
web_pass1=a81be4e9b20632860d20a64c054c4150
web_user=admin
web_user1=user
webuilog=1
2018-09-05 17:00:43,088:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fprintenv (0.05 s)
2018-09-05 17:00:43,096:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv pwmreglow '37376'
2018-09-05 17:00:46,993:DEBUG    Exit code= 0
2018-09-05 17:00:46,993:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv pwmreglow '37376' (3.9 s)
2018-09-05 17:00:47,002:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv gain2 '25'
2018-09-05 17:00:51,095:DEBUG    Exit code= 0
2018-09-05 17:00:51,095:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv gain2 '25' (4.09 s)
2018-09-05 17:00:51,102:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv named_block_size '0x2800000'
2018-09-05 17:00:55,134:DEBUG    Exit code= 0
2018-09-05 17:00:55,134:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv named_block_size '0x2800000' (4.03 s)
2018-09-05 17:00:55,144:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ipaddr '10.102.81.61'
2018-09-05 17:00:59,344:DEBUG    Exit code= 0
2018-09-05 17:00:59,344:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ipaddr '10.102.81.61' (4.2 s)
2018-09-05 17:00:59,354:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ptp1ppsen '0'
2018-09-05 17:01:03,573:DEBUG    Exit code= 0
2018-09-05 17:01:03,573:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ptp1ppsen '0' (4.22 s)
2018-09-05 17:01:03,582:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv autoload 'n'
2018-09-05 17:01:06,144:DEBUG    Exit code= 0
2018-09-05 17:01:06,144:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv autoload 'n' (2.56 s)
2018-09-05 17:01:06,154:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv syncby 'gps'
2018-09-05 17:01:08,654:DEBUG    Exit code= 0
2018-09-05 17:01:08,654:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv syncby 'gps' (2.5 s)
2018-09-05 17:01:08,668:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv boardname 'zen'
2018-09-05 17:01:11,194:DEBUG    Exit code= 0
2018-09-05 17:01:11,194:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv boardname 'zen' (2.53 s)
2018-09-05 17:01:11,203:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv loadaddr '0x20000000'
2018-09-05 17:01:13,744:DEBUG    Exit code= 0
2018-09-05 17:01:13,744:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv loadaddr '0x20000000' (2.54 s)
2018-09-05 17:01:13,753:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ucliovrd '0'
2018-09-05 17:01:16,285:DEBUG    Exit code= 0
2018-09-05 17:01:16,285:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ucliovrd '0' (2.53 s)
2018-09-05 17:01:16,293:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv swloadby 'flash'
2018-09-05 17:01:18,773:DEBUG    Exit code= 0
2018-09-05 17:01:18,773:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv swloadby 'flash' (2.48 s)
2018-09-05 17:01:18,782:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv logdispen '2'
2018-09-05 17:01:21,315:DEBUG    Exit code= 0
2018-09-05 17:01:21,315:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv logdispen '2' (2.53 s)
2018-09-05 17:01:21,322:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bootdelay '0'
2018-09-05 17:01:23,914:DEBUG    Exit code= 0
2018-09-05 17:01:23,914:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bootdelay '0' (2.59 s)
2018-09-05 17:01:23,923:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv enable_zen5_gpio18 '1'
2018-09-05 17:01:26,474:DEBUG    Exit code= 0
2018-09-05 17:01:26,474:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv enable_zen5_gpio18 '1' (2.55 s)
2018-09-05 17:01:26,483:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv default_load 'setenv flash_rd_addr 0x18320000 && setenv flash_os_addr 0x17E20000 && setenv img_no 0 && run load_imgs'
2018-09-05 17:01:29,055:DEBUG    Exit code= 0
2018-09-05 17:01:29,055:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv default_load 'setenv flash_rd_addr 0x18320000 && setenv flash_os_addr 0x17E20000 && setenv img_no 0 && run load_imgs' (2.57 s)
2018-09-05 17:01:29,062:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv baudrate_uart1 '19200'
2018-09-05 17:01:31,604:DEBUG    Exit code= 0
2018-09-05 17:01:31,605:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv baudrate_uart1 '19200' (2.54 s)
2018-09-05 17:01:31,611:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bootby 'flash'
2018-09-05 17:01:34,184:DEBUG    Exit code= 0
2018-09-05 17:01:34,184:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bootby 'flash' (2.57 s)
2018-09-05 17:01:34,194:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ls 'fatls ide 0'
2018-09-05 17:01:36,714:DEBUG    Exit code= 0
2018-09-05 17:01:36,714:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ls 'fatls ide 0' (2.52 s)
2018-09-05 17:01:36,724:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv namedalloc 'namedalloc dsp-dump 0x400000 0x7f4D0000; namedalloc cazac 0x630000 0x7f8D0000; namedalloc pf4cazac 0x13000 0x84000000; namedalloc cpu-dsp-if 0x100000 0x7ff00000; namedalloc dsp-log-buf 0x4000000 0x80000000; namedalloc initrd 0x2800000 0x30800000;'
2018-09-05 17:01:39,255:DEBUG    Exit code= 0
2018-09-05 17:01:39,255:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv namedalloc 'namedalloc dsp-dump 0x400000 0x7f4D0000; namedalloc cazac 0x630000 0x7f8D0000; namedalloc pf4cazac 0x13000 0x84000000; namedalloc cpu-dsp-if 0x100000 0x7ff00000; namedalloc dsp-log-buf 0x4000000 0x80000000; namedalloc initrd 0x2800000 0x30800000;' (2.53 s)
2018-09-05 17:01:39,263:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv pseudowww '1'
2018-09-05 17:01:41,795:DEBUG    Exit code= 0
2018-09-05 17:01:41,795:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv pseudowww '1' (2.53 s)
2018-09-05 17:01:41,802:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv gpstestinterval '10'
2018-09-05 17:01:44,355:DEBUG    Exit code= 0
2018-09-05 17:01:44,355:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv gpstestinterval '10' (2.55 s)
2018-09-05 17:01:44,364:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv web_pass '456b7016a916a4b178dd72b947c152b7'
2018-09-05 17:01:46,914:DEBUG    Exit code= 0
2018-09-05 17:01:46,914:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv web_pass '456b7016a916a4b178dd72b947c152b7' (2.55 s)
2018-09-05 17:01:46,921:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv txfreq '1825'
2018-09-05 17:01:49,453:DEBUG    Exit code= 0
2018-09-05 17:01:49,454:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv txfreq '1825' (2.53 s)
2018-09-05 17:01:49,464:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv factory_load 'setenv flash_rd_addr 0x1C200000 && setenv flash_os_addr 0x1BD00000 && setenv img_no 1 && run load_imgs'
2018-09-05 17:01:51,993:DEBUG    Exit code= 0
2018-09-05 17:01:51,993:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv factory_load 'setenv flash_rd_addr 0x1C200000 && setenv flash_os_addr 0x1BD00000 && setenv img_no 1 && run load_imgs' (2.53 s)
2018-09-05 17:01:52,002:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv webuilog '1'
2018-09-05 17:01:54,546:DEBUG    Exit code= 0
2018-09-05 17:01:54,546:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv webuilog '1' (2.54 s)
2018-09-05 17:01:54,569:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv rxfreq '1730'
2018-09-05 17:01:57,115:DEBUG    Exit code= 0
2018-09-05 17:01:57,115:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv rxfreq '1730' (2.55 s)
2018-09-05 17:01:57,121:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv target 'zen'
2018-09-05 17:01:59,674:DEBUG    Exit code= 0
2018-09-05 17:01:59,674:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv target 'zen' (2.55 s)
2018-09-05 17:01:59,683:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv gpsenablecount '5'
2018-09-05 17:02:02,204:DEBUG    Exit code= 0
2018-09-05 17:02:02,204:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv gpsenablecount '5' (2.52 s)
2018-09-05 17:02:02,213:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv pwdb_in_flash '1'
2018-09-05 17:02:04,753:DEBUG    Exit code= 0
2018-09-05 17:02:04,753:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv pwdb_in_flash '1' (2.54 s)
2018-09-05 17:02:04,763:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv enbctrlrf '1'
2018-09-05 17:02:07,315:DEBUG    Exit code= 0
2018-09-05 17:02:07,315:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv enbctrlrf '1' (2.55 s)
2018-09-05 17:02:07,325:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv mode 'e2e'
2018-09-05 17:02:09,884:DEBUG    Exit code= 0
2018-09-05 17:02:09,884:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv mode 'e2e' (2.56 s)
2018-09-05 17:02:09,894:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv gain1 '25'
2018-09-05 17:02:12,464:DEBUG    Exit code= 0
2018-09-05 17:02:12,464:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv gain1 '25' (2.57 s)
2018-09-05 17:02:12,473:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv i2cinit 'i2c reset'
2018-09-05 17:02:15,043:DEBUG    Exit code= 0
2018-09-05 17:02:15,043:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv i2cinit 'i2c reset' (2.57 s)
2018-09-05 17:02:15,052:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv web_user1 'user'
2018-09-05 17:02:17,625:DEBUG    Exit code= 0
2018-09-05 17:02:17,625:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv web_user1 'user' (2.57 s)
2018-09-05 17:02:17,640:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bootcbyflash 'run default_load || run factory_load; run boot_linux'
2018-09-05 17:02:20,253:DEBUG    Exit code= 0
2018-09-05 17:02:20,255:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bootcbyflash 'run default_load || run factory_load; run boot_linux' (2.62 s)
2018-09-05 17:02:20,263:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ethact 'octeth0'
2018-09-05 17:02:22,815:DEBUG    Exit code= 0
2018-09-05 17:02:22,815:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ethact 'octeth0' (2.55 s)
2018-09-05 17:02:22,822:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv burn_app 'erase $(flash_unused_addr) +$(filesize);cp.b $(fileaddr) $(flash_unused_addr) $(filesize)'
2018-09-05 17:02:25,345:DEBUG    Exit code= 0
2018-09-05 17:02:25,345:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv burn_app 'erase $(flash_unused_addr) +$(filesize);cp.b $(fileaddr) $(flash_unused_addr) $(filesize)' (2.52 s)
2018-09-05 17:02:25,352:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv httpdenable '1'
2018-09-05 17:02:27,934:DEBUG    Exit code= 0
2018-09-05 17:02:27,934:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv httpdenable '1' (2.58 s)
2018-09-05 17:02:27,941:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv mtdids 'nor0=octeon_nor0'
2018-09-05 17:02:30,776:DEBUG    Exit code= 0
2018-09-05 17:02:30,776:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv mtdids 'nor0=octeon_nor0' (2.83 s)
2018-09-05 17:02:30,785:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv atten2 '18'
2018-09-05 17:02:32,565:DEBUG    Exit code= 0
2018-09-05 17:02:32,566:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv atten2 '18' (1.78 s)
2018-09-05 17:02:32,575:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv atten1 '18'
2018-09-05 17:02:34,446:DEBUG    Exit code= 0
2018-09-05 17:02:34,447:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv atten1 '18' (1.87 s)
2018-09-05 17:02:34,454:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bootcmd 'run i2cinit; run namedalloc; run bootcby${bootby}'
2018-09-05 17:02:36,316:DEBUG    Exit code= 0
2018-09-05 17:02:36,316:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bootcmd 'run i2cinit; run namedalloc; run bootcby${bootby}' (1.86 s)
2018-09-05 17:02:36,325:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv mode_test 'dl'
2018-09-05 17:02:38,157:DEBUG    Exit code= 0
2018-09-05 17:02:38,157:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv mode_test 'dl' (1.83 s)
2018-09-05 17:02:38,165:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv dhcpenable '0'
2018-09-05 17:02:40,098:DEBUG    Exit code= 0
2018-09-05 17:02:40,098:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv dhcpenable '0' (1.93 s)
2018-09-05 17:02:40,105:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv named_block_addr '0x30800000'
2018-09-05 17:02:41,977:DEBUG    Exit code= 0
2018-09-05 17:02:41,977:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv named_block_addr '0x30800000' (1.87 s)
2018-09-05 17:02:41,987:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv linux_cf 'fatload ide 0 $(loadaddr) vmlinux.64;bootoctlinux $(loadaddr)'
2018-09-05 17:02:43,917:DEBUG    Exit code= 0
2018-09-05 17:02:43,917:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv linux_cf 'fatload ide 0 $(loadaddr) vmlinux.64;bootoctlinux $(loadaddr)' (1.93 s)
2018-09-05 17:02:43,927:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv load_imgs 'cp.l ${flash_rd_addr} 0x30800000 0xA00000 && gunzip ${flash_os_addr} 0x20000000'
2018-09-05 17:02:45,778:DEBUG    Exit code= 0
2018-09-05 17:02:45,778:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv load_imgs 'cp.l ${flash_rd_addr} 0x30800000 0xA00000 && gunzip ${flash_os_addr} 0x20000000' (1.85 s)
2018-09-05 17:02:45,786:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv tip '1'
2018-09-05 17:02:47,737:DEBUG    Exit code= 0
2018-09-05 17:02:47,737:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv tip '1' (1.95 s)
2018-09-05 17:02:47,746:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv acsurl ''
2018-09-05 17:02:49,608:DEBUG    Exit code= 0
2018-09-05 17:02:49,608:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv acsurl '' (1.86 s)
2018-09-05 17:02:49,615:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bootfile 'pxelinux.0'
2018-09-05 17:02:51,516:DEBUG    Exit code= 0
2018-09-05 17:02:51,517:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bootfile 'pxelinux.0' (1.9 s)
2018-09-05 17:02:51,526:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv baudrate ''
2018-09-05 17:02:53,408:DEBUG    Exit code= 0
2018-09-05 17:02:53,408:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv baudrate '' (1.88 s)
2018-09-05 17:02:53,417:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv web_pass1 'a81be4e9b20632860d20a64c054c4150'
2018-09-05 17:02:55,368:DEBUG    Exit code= 0
2018-09-05 17:02:55,368:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv web_pass1 'a81be4e9b20632860d20a64c054c4150' (1.95 s)
2018-09-05 17:02:55,377:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bf 'bootoct $(flash_unused_addr) forceboot numcores=$(numcores)'
2018-09-05 17:02:57,328:DEBUG    Exit code= 0
2018-09-05 17:02:57,329:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bf 'bootoct $(flash_unused_addr) forceboot numcores=$(numcores)' (1.95 s)
2018-09-05 17:02:57,338:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ptpenable '0'
2018-09-05 17:02:59,309:DEBUG    Exit code= 0
2018-09-05 17:02:59,309:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ptpenable '0' (1.97 s)
2018-09-05 17:02:59,316:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv gatewayip '10.102.81.1'
2018-09-05 17:03:01,289:DEBUG    Exit code= 0
2018-09-05 17:03:01,289:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv gatewayip '10.102.81.1' (1.97 s)
2018-09-05 17:03:01,298:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv serverip '10.102.81.50'
2018-09-05 17:03:03,269:DEBUG    Exit code= 0
2018-09-05 17:03:03,269:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv serverip '10.102.81.50' (1.97 s)
2018-09-05 17:03:03,278:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv acsenable '0'
2018-09-05 17:03:05,249:DEBUG    Exit code= 0
2018-09-05 17:03:05,249:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv acsenable '0' (1.97 s)
2018-09-05 17:03:05,257:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv txpower '30'
2018-09-05 17:03:07,209:DEBUG    Exit code= 0
2018-09-05 17:03:07,209:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv txpower '30' (1.95 s)
2018-09-05 17:03:07,217:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv mk_ubootenv '1'
2018-09-05 17:03:09,187:DEBUG    Exit code= 0
2018-09-05 17:03:09,187:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv mk_ubootenv '1' (1.97 s)
2018-09-05 17:03:09,196:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bw '10'
2018-09-05 17:03:11,229:DEBUG    Exit code= 0
2018-09-05 17:03:11,229:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bw '10' (2.03 s)
2018-09-05 17:03:11,237:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv bootcbytftp 'tftp 0x21000000 lsm_os.gz; gunzip 0x21000000 0x20000000 0x1000000; tftp 0x30800000 lsm_rd.gz; bootoctlinux 0x20000000 coremask=0x7 endbootargs rd_name=initrd mem=512M;'
2018-09-05 17:03:13,229:DEBUG    Exit code= 0
2018-09-05 17:03:13,229:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv bootcbytftp 'tftp 0x21000000 lsm_os.gz; gunzip 0x21000000 0x20000000 0x1000000; tftp 0x30800000 lsm_rd.gz; bootoctlinux 0x20000000 coremask=0x7 endbootargs rd_name=initrd mem=512M;' (1.99 s)
2018-09-05 17:03:13,239:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv dnsip '8.8.8.8'
2018-09-05 17:03:15,188:DEBUG    Exit code= 0
2018-09-05 17:03:15,188:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv dnsip '8.8.8.8' (1.95 s)
2018-09-05 17:03:15,197:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv tcxo 'pwm'
2018-09-05 17:03:17,148:DEBUG    Exit code= 0
2018-09-05 17:03:17,148:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv tcxo 'pwm' (1.95 s)
2018-09-05 17:03:17,165:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv web_user 'admin'
2018-09-05 17:03:19,138:DEBUG    Exit code= 0
2018-09-05 17:03:19,138:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv web_user 'admin' (1.97 s)
2018-09-05 17:03:19,148:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv ovrdrfdsp '1'
2018-09-05 17:03:21,138:DEBUG    Exit code= 0
2018-09-05 17:03:21,140:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv ovrdrfdsp '1' (1.99 s)
2018-09-05 17:03:21,148:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv numcores '4'
2018-09-05 17:03:23,119:DEBUG    Exit code= 0
2018-09-05 17:03:23,119:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv numcores '4' (1.97 s)
2018-09-05 17:03:23,128:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv gpsenable ''
2018-09-05 17:03:25,160:DEBUG    Exit code= 0
2018-09-05 17:03:25,160:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv gpsenable '' (2.03 s)
2018-09-05 17:03:25,167:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv partition 'nor0,5'
2018-09-05 17:03:27,158:DEBUG    Exit code= 0
2018-09-05 17:03:27,160:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv partition 'nor0,5' (1.99 s)
2018-09-05 17:03:27,167:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv startapp '1'
2018-09-05 17:03:29,118:DEBUG    Exit code= 0
2018-09-05 17:03:29,118:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv startapp '1' (1.95 s)
2018-09-05 17:03:29,127:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv pwmreghigh '24744'
2018-09-05 17:03:31,078:DEBUG    Exit code= 0
2018-09-05 17:03:31,079:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv pwmreghigh '24744' (1.95 s)
2018-09-05 17:03:31,086:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv boot_linux 'bootoctlinux 0x20000000 coremask=0x7 endbootargs rd_name=initrd mem=512M img=${img_no}'
2018-09-05 17:03:33,089:DEBUG    Exit code= 0
2018-09-05 17:03:33,089:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv boot_linux 'bootoctlinux 0x20000000 coremask=0x7 endbootargs rd_name=initrd mem=512M img=${img_no}' (2.0 s)
2018-09-05 17:03:33,098:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv cfgloadby 'flash'
2018-09-05 17:03:35,029:DEBUG    Exit code= 0
2018-09-05 17:03:35,029:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv cfgloadby 'flash' (1.93 s)
2018-09-05 17:03:35,038:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv rftarget 'ad9362'
2018-09-05 17:03:36,980:DEBUG    Exit code= 0
2018-09-05 17:03:36,980:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv rftarget 'ad9362' (1.94 s)
2018-09-05 17:03:36,986:DEBUG    Timeout 10.0s, TTY=False. Command: fsetenv netmask '255.255.255.0'
2018-09-05 17:03:39,000:DEBUG    Exit code= 0
2018-09-05 17:03:39,000:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: fsetenv netmask '255.255.255.0' (2.01 s)
2018-09-05 17:03:39,029:DEBUG    Timeout 1.0s, TTY=False. Command: reboot
2018-09-05 17:03:40,051:INFO     COMMAND TIMEOUT REACHED
2018-09-05 17:03:40,051:DEBUG    Exit code= -1
2018-09-05 17:03:40,052:INFO     SERVICE HANDLING - Timeout 1.0s, TTY=False. Command: reboot (1.02 s)
2018-09-05 17:03:40,062:DEBUG    Closing SSH connection
2018-09-05 17:03:40,062:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:40,068:DEBUG    


2018-09-05 17:03:40,068:INFO     SERVICE INITIALIZED
2018-09-05 17:03:40,069:DEBUG    LOG =DEBUG
2018-09-05 17:03:40,069:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:40,069:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:03:42,072:DEBUG    Unexpected error occured while handling request
2018-09-05 17:03:42,072:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:42,072:WARNING  Client error [timed out timed out]
2018-09-05 17:03:42,075:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:43,084:DEBUG    Closing SSH connection
2018-09-05 17:03:43,085:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:43,089:DEBUG    


2018-09-05 17:03:43,089:INFO     SERVICE INITIALIZED
2018-09-05 17:03:43,091:DEBUG    LOG =DEBUG
2018-09-05 17:03:43,091:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:43,091:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:03:45,094:DEBUG    Unexpected error occured while handling request
2018-09-05 17:03:45,094:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:45,094:WARNING  Client error [timed out timed out]
2018-09-05 17:03:45,095:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:46,102:DEBUG    Closing SSH connection
2018-09-05 17:03:46,102:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:46,108:DEBUG    


2018-09-05 17:03:46,108:INFO     SERVICE INITIALIZED
2018-09-05 17:03:46,108:DEBUG    LOG =DEBUG
2018-09-05 17:03:46,108:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:46,108:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:03:48,111:DEBUG    Unexpected error occured while handling request
2018-09-05 17:03:48,111:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:48,111:WARNING  Client error [timed out timed out]
2018-09-05 17:03:48,112:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:49,121:DEBUG    Closing SSH connection
2018-09-05 17:03:49,121:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:49,127:DEBUG    


2018-09-05 17:03:49,127:INFO     SERVICE INITIALIZED
2018-09-05 17:03:49,127:DEBUG    LOG =DEBUG
2018-09-05 17:03:49,127:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:49,127:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:03:51,128:DEBUG    Unexpected error occured while handling request
2018-09-05 17:03:51,128:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:51,128:WARNING  Client error [timed out timed out]
2018-09-05 17:03:51,131:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:52,138:DEBUG    Closing SSH connection
2018-09-05 17:03:52,138:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:52,144:DEBUG    


2018-09-05 17:03:52,144:INFO     SERVICE INITIALIZED
2018-09-05 17:03:52,144:DEBUG    LOG =DEBUG
2018-09-05 17:03:52,144:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:52,144:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:03:54,148:DEBUG    Unexpected error occured while handling request
2018-09-05 17:03:54,148:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:54,148:WARNING  Client error [timed out timed out]
2018-09-05 17:03:54,150:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:55,157:DEBUG    Closing SSH connection
2018-09-05 17:03:55,157:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:55,163:DEBUG    


2018-09-05 17:03:55,163:INFO     SERVICE INITIALIZED
2018-09-05 17:03:55,163:DEBUG    LOG =DEBUG
2018-09-05 17:03:55,163:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:55,163:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:03:57,165:DEBUG    Unexpected error occured while handling request
2018-09-05 17:03:57,165:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:57,165:WARNING  Client error [timed out timed out]
2018-09-05 17:03:57,167:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:03:58,174:DEBUG    Closing SSH connection
2018-09-05 17:03:58,174:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:03:58,180:DEBUG    


2018-09-05 17:03:58,180:INFO     SERVICE INITIALIZED
2018-09-05 17:03:58,180:DEBUG    LOG =DEBUG
2018-09-05 17:03:58,180:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:03:58,181:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:00,184:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:00,184:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:00,186:WARNING  Client error [timed out timed out]
2018-09-05 17:04:00,186:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:01,193:DEBUG    Closing SSH connection
2018-09-05 17:04:01,193:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:01,200:DEBUG    


2018-09-05 17:04:01,200:INFO     SERVICE INITIALIZED
2018-09-05 17:04:01,200:DEBUG    LOG =DEBUG
2018-09-05 17:04:01,200:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:01,200:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:03,203:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:03,203:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:03,203:WARNING  Client error [timed out timed out]
2018-09-05 17:04:03,206:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:04,213:DEBUG    Closing SSH connection
2018-09-05 17:04:04,213:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:04,217:DEBUG    


2018-09-05 17:04:04,217:INFO     SERVICE INITIALIZED
2018-09-05 17:04:04,219:DEBUG    LOG =DEBUG
2018-09-05 17:04:04,219:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:04,219:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:06,221:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:06,221:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:06,221:WARNING  Client error [timed out timed out]
2018-09-05 17:04:06,223:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:07,232:DEBUG    Closing SSH connection
2018-09-05 17:04:07,232:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:07,236:DEBUG    


2018-09-05 17:04:07,237:INFO     SERVICE INITIALIZED
2018-09-05 17:04:07,237:DEBUG    LOG =DEBUG
2018-09-05 17:04:07,237:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:07,237:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:09,240:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:09,240:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:09,240:WARNING  Client error [timed out timed out]
2018-09-05 17:04:09,243:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:10,250:DEBUG    Closing SSH connection
2018-09-05 17:04:10,250:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:10,255:DEBUG    


2018-09-05 17:04:10,255:INFO     SERVICE INITIALIZED
2018-09-05 17:04:10,255:DEBUG    LOG =DEBUG
2018-09-05 17:04:10,256:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:10,256:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:12,257:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:12,257:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:12,257:WARNING  Client error [timed out timed out]
2018-09-05 17:04:12,259:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:13,266:DEBUG    Closing SSH connection
2018-09-05 17:04:13,266:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:13,273:DEBUG    


2018-09-05 17:04:13,273:INFO     SERVICE INITIALIZED
2018-09-05 17:04:13,273:DEBUG    LOG =DEBUG
2018-09-05 17:04:13,273:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:13,273:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:15,276:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:15,276:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:15,276:WARNING  Client error [timed out timed out]
2018-09-05 17:04:15,278:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:16,285:DEBUG    Closing SSH connection
2018-09-05 17:04:16,285:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:16,289:DEBUG    


2018-09-05 17:04:16,290:INFO     SERVICE INITIALIZED
2018-09-05 17:04:16,290:DEBUG    LOG =DEBUG
2018-09-05 17:04:16,290:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:16,290:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:18,293:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:18,293:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:18,293:WARNING  Client error [timed out timed out]
2018-09-05 17:04:18,296:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:19,302:DEBUG    Closing SSH connection
2018-09-05 17:04:19,302:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:19,309:DEBUG    


2018-09-05 17:04:19,309:INFO     SERVICE INITIALIZED
2018-09-05 17:04:19,309:DEBUG    LOG =DEBUG
2018-09-05 17:04:19,309:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:19,309:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:21,312:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:21,312:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:21,312:WARNING  Client error [timed out timed out]
2018-09-05 17:04:21,313:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:22,321:DEBUG    Closing SSH connection
2018-09-05 17:04:22,321:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:22,325:DEBUG    


2018-09-05 17:04:22,325:INFO     SERVICE INITIALIZED
2018-09-05 17:04:22,325:DEBUG    LOG =DEBUG
2018-09-05 17:04:22,325:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:22,325:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:24,328:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:24,328:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:24,328:WARNING  Client error [timed out timed out]
2018-09-05 17:04:24,329:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:25,336:DEBUG    Closing SSH connection
2018-09-05 17:04:25,336:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:25,342:DEBUG    


2018-09-05 17:04:25,342:INFO     SERVICE INITIALIZED
2018-09-05 17:04:25,342:DEBUG    LOG =DEBUG
2018-09-05 17:04:25,342:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:25,344:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:27,345:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:27,345:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:27,345:WARNING  Client error [timed out timed out]
2018-09-05 17:04:27,348:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:28,355:DEBUG    Closing SSH connection
2018-09-05 17:04:28,355:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:28,361:DEBUG    


2018-09-05 17:04:28,361:INFO     SERVICE INITIALIZED
2018-09-05 17:04:28,361:DEBUG    LOG =DEBUG
2018-09-05 17:04:28,361:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:28,361:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:30,364:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:30,364:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:30,364:WARNING  Client error [timed out timed out]
2018-09-05 17:04:30,365:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:31,371:DEBUG    Closing SSH connection
2018-09-05 17:04:31,371:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:31,377:DEBUG    


2018-09-05 17:04:31,377:INFO     SERVICE INITIALIZED
2018-09-05 17:04:31,377:DEBUG    LOG =DEBUG
2018-09-05 17:04:31,378:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:31,378:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:33,381:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:33,381:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:33,381:WARNING  Client error [timed out timed out]
2018-09-05 17:04:33,382:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:34,390:DEBUG    Closing SSH connection
2018-09-05 17:04:34,390:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:34,395:DEBUG    


2018-09-05 17:04:34,395:INFO     SERVICE INITIALIZED
2018-09-05 17:04:34,395:DEBUG    LOG =DEBUG
2018-09-05 17:04:34,395:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:34,397:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:36,400:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:36,400:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:36,400:WARNING  Client error [timed out timed out]
2018-09-05 17:04:36,401:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:37,410:DEBUG    Closing SSH connection
2018-09-05 17:04:37,410:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:37,414:DEBUG    


2018-09-05 17:04:37,414:INFO     SERVICE INITIALIZED
2018-09-05 17:04:37,415:DEBUG    LOG =DEBUG
2018-09-05 17:04:37,415:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:37,415:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:39,417:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:39,417:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:39,417:WARNING  Client error [timed out timed out]
2018-09-05 17:04:39,418:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:40,427:DEBUG    Closing SSH connection
2018-09-05 17:04:40,427:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:40,433:DEBUG    


2018-09-05 17:04:40,433:INFO     SERVICE INITIALIZED
2018-09-05 17:04:40,434:DEBUG    LOG =DEBUG
2018-09-05 17:04:40,434:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:40,434:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:42,436:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:42,436:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:42,436:WARNING  Client error [timed out timed out]
2018-09-05 17:04:42,437:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:43,446:DEBUG    Closing SSH connection
2018-09-05 17:04:43,446:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:43,450:DEBUG    


2018-09-05 17:04:43,450:INFO     SERVICE INITIALIZED
2018-09-05 17:04:43,451:DEBUG    LOG =DEBUG
2018-09-05 17:04:43,451:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:43,451:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:45,453:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:45,453:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:45,453:WARNING  Client error [timed out timed out]
2018-09-05 17:04:45,456:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:46,463:DEBUG    Closing SSH connection
2018-09-05 17:04:46,463:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:46,469:DEBUG    


2018-09-05 17:04:46,469:INFO     SERVICE INITIALIZED
2018-09-05 17:04:46,470:DEBUG    LOG =DEBUG
2018-09-05 17:04:46,470:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:46,470:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:48,471:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:48,471:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:48,471:WARNING  Client error [timed out timed out]
2018-09-05 17:04:48,473:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:49,480:DEBUG    Closing SSH connection
2018-09-05 17:04:49,482:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:49,486:DEBUG    


2018-09-05 17:04:49,486:INFO     SERVICE INITIALIZED
2018-09-05 17:04:49,486:DEBUG    LOG =DEBUG
2018-09-05 17:04:49,487:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:49,487:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:04:51,489:DEBUG    Unexpected error occured while handling request
2018-09-05 17:04:51,489:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:51,489:WARNING  Client error [timed out timed out]
2018-09-05 17:04:51,490:DEBUG    Traceback (most recent call last):
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 205, in exception_handling
    response_object = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 193, in process_std_route
    response_object = function(self, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base.py", line 371, in new_service
    service.base_service_config(config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 101, in _log_entry
    return_value = function(self, *args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 150, in base_service_config
    self._standard_function_error_handling(self.service_config, config)
  File "c:\git_files\oc-lte-testbench\src\nute\nute\service\base_service.py", line 155, in _standard_function_error_handling
    return function(*args, **kwargs)
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 41, in service_config
    self.connect()
  File "c:\git_files\oc-lte-testbench\src\opentest\opentest\services\ssh_service.py", line 52, in connect
    raise ServiceError("%s %s" % (str(e), e.message))
ServiceError: timed out timed out

2018-09-05 17:04:52,499:DEBUG    Closing SSH connection
2018-09-05 17:04:52,499:INFO     SERVICE SHUTDOWN COMPLETE
2018-09-05 17:04:52,503:DEBUG    


2018-09-05 17:04:52,503:INFO     SERVICE INITIALIZED
2018-09-05 17:04:52,505:DEBUG    LOG =DEBUG
2018-09-05 17:04:52,505:DEBUG    Initiating SSH connection at 10.102.81.61
2018-09-05 17:04:52,505:DEBUG    10.102.81.61:22, user=root, password=cavium.lte
2018-09-05 17:05:02,607:INFO     SERVICE CONFIGURATION - LOG =DEBUG - 10.102.81.61:22, user=root, password=cavium.lte (10.1 s)
2018-09-05 17:05:02,612:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:02,625:DEBUG    Exit code= 0
2018-09-05 17:05:02,625:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:02,625:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:04,632:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:04,647:DEBUG    Exit code= 0
2018-09-05 17:05:04,647:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:04,648:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:06,654:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:06,668:DEBUG    Exit code= 0
2018-09-05 17:05:06,670:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:06,670:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:08,677:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:08,687:DEBUG    Exit code= 0
2018-09-05 17:05:08,687:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:08,687:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:10,696:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:10,710:DEBUG    Exit code= 0
2018-09-05 17:05:10,710:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:10,710:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:12,717:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:12,733:DEBUG    Exit code= 0
2018-09-05 17:05:12,733:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:12,733:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:14,742:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:14,753:DEBUG    Exit code= 0
2018-09-05 17:05:14,753:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:14,753:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:16,759:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:16,772:DEBUG    Exit code= 0
2018-09-05 17:05:16,772:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:16,772:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:18,779:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:18,793:DEBUG    Exit code= 0
2018-09-05 17:05:18,793:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:18,793:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:20,802:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:20,816:DEBUG    Exit code= 0
2018-09-05 17:05:20,816:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:20,816:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:22,825:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:22,838:DEBUG    Exit code= 0
2018-09-05 17:05:22,838:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
2018-09-05 17:05:22,838:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:24,845:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:24,859:DEBUG    Exit code= 0
2018-09-05 17:05:24,859:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:24,859:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:26,868:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:26,881:DEBUG    Exit code= 0
2018-09-05 17:05:26,881:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:26,882:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:28,891:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:28,904:DEBUG    Exit code= 0
2018-09-05 17:05:28,904:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:28,904:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:30,911:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:30,924:DEBUG    Exit code= 0
2018-09-05 17:05:30,924:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:30,924:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:32,933:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:32,944:DEBUG    Exit code= 0
2018-09-05 17:05:32,944:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:32,944:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:34,950:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:34,964:DEBUG    Exit code= 0
2018-09-05 17:05:34,964:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:34,964:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:36,973:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:36,987:DEBUG    Exit code= 0
2018-09-05 17:05:36,987:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:36,987:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:38,997:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:39,012:DEBUG    Exit code= 0
2018-09-05 17:05:39,012:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:39,012:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:41,019:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:41,065:DEBUG    Exit code= 0
2018-09-05 17:05:41,065:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:41,065:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.05 s)
2018-09-05 17:05:43,072:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:43,086:DEBUG    Exit code= 0
2018-09-05 17:05:43,086:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:43,086:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:45,094:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:45,107:DEBUG    Exit code= 0
2018-09-05 17:05:45,108:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:45,108:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:47,115:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:47,130:DEBUG    Exit code= 0
2018-09-05 17:05:47,131:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:47,131:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:49,141:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:49,157:DEBUG    Exit code= 0
2018-09-05 17:05:49,157:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:49,157:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:51,164:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:51,180:DEBUG    Exit code= 0
2018-09-05 17:05:51,180:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:51,180:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:53,188:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:53,203:DEBUG    Exit code= 0
2018-09-05 17:05:53,203:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:53,203:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:05:55,211:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:55,223:DEBUG    Exit code= 0
2018-09-05 17:05:55,223:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:55,223:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:57,232:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:57,246:DEBUG    Exit code= 0
2018-09-05 17:05:57,246:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:57,246:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:05:59,256:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:05:59,269:DEBUG    Exit code= 0
2018-09-05 17:05:59,269:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:05:59,269:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:01,286:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:01,299:DEBUG    Exit code= 0
2018-09-05 17:06:01,299:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:01,299:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:03,308:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:03,322:DEBUG    Exit code= 0
2018-09-05 17:06:03,323:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:03,323:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:05,331:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:05,344:DEBUG    Exit code= 0
2018-09-05 17:06:05,344:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:05,344:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:07,352:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:07,367:DEBUG    Exit code= 0
2018-09-05 17:06:07,367:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:07,368:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:09,375:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:09,388:DEBUG    Exit code= 0
2018-09-05 17:06:09,388:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:09,388:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:11,398:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:11,413:DEBUG    Exit code= 0
2018-09-05 17:06:11,413:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:11,413:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:13,420:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:13,434:DEBUG    Exit code= 0
2018-09-05 17:06:13,434:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:13,434:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:15,441:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:15,459:DEBUG    Exit code= 0
2018-09-05 17:06:15,459:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:15,460:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:17,467:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:17,483:DEBUG    Exit code= 0
2018-09-05 17:06:17,483:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:17,483:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:19,490:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:19,516:DEBUG    Exit code= 0
2018-09-05 17:06:19,516:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:19,516:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.03 s)
2018-09-05 17:06:21,523:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:21,539:DEBUG    Exit code= 0
2018-09-05 17:06:21,539:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:21,539:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:23,548:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:23,561:DEBUG    Exit code= 0
2018-09-05 17:06:23,561:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:23,561:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:25,569:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:25,585:DEBUG    Exit code= 0
2018-09-05 17:06:25,585:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:25,585:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:27,592:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:27,607:DEBUG    Exit code= 0
2018-09-05 17:06:27,607:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:27,607:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:29,614:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:29,641:DEBUG    Exit code= 0
2018-09-05 17:06:29,641:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:29,641:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.03 s)
2018-09-05 17:06:31,648:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:31,678:DEBUG    Exit code= 0
2018-09-05 17:06:31,680:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:31,680:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.03 s)
2018-09-05 17:06:33,687:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:33,706:DEBUG    Exit code= 0
2018-09-05 17:06:33,707:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:33,707:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:35,713:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:35,726:DEBUG    Exit code= 0
2018-09-05 17:06:35,727:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:35,727:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:37,736:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:37,752:DEBUG    Exit code= 0
2018-09-05 17:06:37,753:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:37,753:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:39,760:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:39,776:DEBUG    Exit code= 0
2018-09-05 17:06:39,776:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:39,776:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:41,785:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:41,798:DEBUG    Exit code= 0
2018-09-05 17:06:41,798:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:41,798:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:43,806:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:43,823:DEBUG    Exit code= 0
2018-09-05 17:06:43,823:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:43,823:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:45,832:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:45,848:DEBUG    Exit code= 0
2018-09-05 17:06:45,849:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:45,849:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:47,857:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:47,874:DEBUG    Exit code= 0
2018-09-05 17:06:47,875:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:47,875:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:49,882:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:49,894:DEBUG    Exit code= 0
2018-09-05 17:06:49,894:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:49,894:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:51,903:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:51,917:DEBUG    Exit code= 0
2018-09-05 17:06:51,917:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:51,917:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:53,927:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:53,941:DEBUG    Exit code= 0
2018-09-05 17:06:53,941:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:53,941:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:55,950:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:55,967:DEBUG    Exit code= 0
2018-09-05 17:06:55,967:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:55,967:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:06:57,974:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:06:57,987:DEBUG    Exit code= 0
2018-09-05 17:06:57,987:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:06:57,987:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:06:59,999:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:00,013:DEBUG    Exit code= 0
2018-09-05 17:07:00,013:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:00,013:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:02,023:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:02,038:DEBUG    Exit code= 0
2018-09-05 17:07:02,039:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:02,039:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:07:04,046:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:04,059:DEBUG    Exit code= 0
2018-09-05 17:07:04,059:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:04,059:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:06,066:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:06,079:DEBUG    Exit code= 0
2018-09-05 17:07:06,079:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:06,079:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:08,088:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:08,102:DEBUG    Exit code= 0
2018-09-05 17:07:08,102:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:08,102:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:10,109:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:10,122:DEBUG    Exit code= 0
2018-09-05 17:07:10,122:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:10,124:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:12,131:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:12,144:DEBUG    Exit code= 0
2018-09-05 17:07:12,144:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:12,144:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:14,153:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:14,167:DEBUG    Exit code= 0
2018-09-05 17:07:14,167:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:14,167:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:16,177:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:16,191:DEBUG    Exit code= 0
2018-09-05 17:07:16,191:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:16,191:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:18,200:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:18,217:DEBUG    Exit code= 0
2018-09-05 17:07:18,217:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:18,217:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:07:20,230:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:20,246:DEBUG    Exit code= 0
2018-09-05 17:07:20,246:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:20,246:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.02 s)
2018-09-05 17:07:22,253:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:22,266:DEBUG    Exit code= 0
2018-09-05 17:07:22,266:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:22,266:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:24,275:DEBUG    Timeout 10.0s, TTY=False. Command: cat /var/log/messages
2018-09-05 17:07:24,286:DEBUG    Exit code= 0
2018-09-05 17:07:24,286:DEBUG    Jan  1 00:00:18 (none) syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM syslog.info syslogd started: BusyBox v1.20.2
Jan  2 00:00:05 LSM daemon.crit mini_httpd[1364]: bind 0.0.0.0 - Address already in use
Jan  2 00:00:05 LSM daemon.warn mini_httpd[1366]: started as root without requesting chroot(), warning only
Jan  2 00:00:05 LSM daemon.notice mini_httpd[1366]: mini_httpd/1.19 19dec2003 starting on LSM, port 443
Jan  2 00:00:10 LSM cron.info crond[1404]: crond: crond (busybox 1.20.2) started, log level 8
Jan  2 00:01:01 LSM cron.info crond[1404]: crond: USER root pid 2957 cmd /usr/bin/tempcheck.sh
Jan  2 00:02:01 LSM cron.info crond[1404]: crond: USER root pid 3897 cmd /usr/bin/tempcheck.sh
Jan  2 08:03:01 LSM daemon.info init: starting pid 4371, tty '/dev/ttyS0': '/sbin/getty -L ttyS0 115200 vt100 '
Jan  2 00:03:01 LSM cron.info crond[1404]: crond: USER root pid 4373 cmd /usr/bin/tempcheck.sh
2018-09-05 17:07:24,286:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: cat /var/log/messages (0.01 s)
2018-09-05 17:07:24,302:DEBUG    Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx0_predriver1_en
2018-09-05 17:07:24,331:DEBUG    Exit code= 0
2018-09-05 17:07:24,331:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx0_predriver1_en (0.03 s)
2018-09-05 17:07:24,342:DEBUG    Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx0_predriver2_en
2018-09-05 17:07:24,385:DEBUG    Exit code= 0
2018-09-05 17:07:24,385:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx0_predriver2_en (0.04 s)
2018-09-05 17:07:24,394:DEBUG    Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.pa0/state
2018-09-05 17:07:24,438:DEBUG    Exit code= 0
2018-09-05 17:07:24,438:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.pa0/state (0.04 s)
2018-09-05 17:07:24,447:DEBUG    Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx1_predriver1_en
2018-09-05 17:07:24,502:DEBUG    Exit code= 0
2018-09-05 17:07:24,503:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx1_predriver1_en (0.05 s)
2018-09-05 17:07:24,510:DEBUG    Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx1_predriver2_en
2018-09-05 17:07:24,568:DEBUG    Exit code= 0
2018-09-05 17:07:24,568:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.tip/tx1_predriver2_en (0.06 s)
2018-09-05 17:07:24,576:DEBUG    Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.pa1/state
2018-09-05 17:07:24,618:DEBUG    Exit code= 0
2018-09-05 17:07:24,619:INFO     SERVICE HANDLING - Timeout 10.0s, TTY=False. Command: echo "0" > /sys/devices/soc.0/0.pa1/state (0.04 s)
